<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>product_name</name>
   <tag></tag>
   <elementGuidId>44bb9ffe-b33a-4bb2-93b0-a113c277e401</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@id='productTitle']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='productTitle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@id='productTitle']</value>
      <webElementGuid>c340e5ed-7277-4313-9798-7615b2ed488c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
